### ISSUE TITLE
Bug when add extra views in Kanboard

### ISSUE THREAD

**Issue by btd1337** [Confexion/Greenwing#17]
When is added extra views like Calendar and Gantt this bug occurs in small resolutions.

![Captura de tela de 2020-01-16 12-06-24](https://user-images.githubusercontent.com/11943860/72536314-c5800380-3858-11ea-8242-503b53622c1e.png)

**Comment by jbaubree** [comment]
Hi,

Thanks for your report, we are working on issue and will close this when it will be fixed.
Best regards,

Greenwing Team

**Comment by jbaubree** [comment]
Fixed in Greenwing 1.2.2 Version! Thanks for report

**Comment by btd1337** [comment]
@jbaubree this bug persists in small screens (smartphone)

![photo_2020-04-10_16-12-53](https://user-images.githubusercontent.com/11943860/79016790-3a0bcb00-7b46-11ea-8073-faeabf25e0df.jpg)
